desc/urls.py
from django.urls import path

from . import views

app_name = "desc"

urlpatterns = [
    path('', views.DailyLastListView.as_view(), name='daily_list'),
    path('day/<int:pk>/', views.DailyDetailView.as_view(), name='daily_detail'),
    # path('thoughts/feed/', Last_thoughts(), name='thoughts_feed'),
    path('thoughts/search/', views.ThoughtsSearch.as_view(), name='search'),
    path('daily/<str:date>/', views.DailyDetail.as_view(), name='detail'),
    path('last/', views.DailyLastViewSet.as_view(), name='last'),
    path('alltags/', views.AllTagsList.as_view(), name='all_tags')
    # path('thoughts/', views.ThoughtListView.as_view(), name='thoughts'),
    # path('update/<str:date>/', views.ThoughtDetailView.as_view(), name='thought_update'),

]

lifedesc/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from lifedesc import settings

urlpatterns = [
    path('', include('desc.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

desc/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Daily(models.Model):
    """ Main daily indicators
    """
    date = models.DateField('date')
    push_ups = models.IntegerField(default=0)
    squates = models.IntegerField(default=0)  # Приседания
    weight = models.DecimalField(decimal_places=1, max_digits=3, default=0.0)
    steps = models.IntegerField(default=0)
    sleeptime = models.DurationField(default='00:00:00')
    deep_sleeptime = models.DurationField(default='00:00:00')
    temperature = models.DecimalField(decimal_places=1, max_digits=3, default=35.0)
    sa = models.IntegerField(default=0)  # Sleep assessment - оценка сна

    class Meta:
        db_table = 'daily'
        # managed = False
        verbose_name_plural = 'Dailies'

    def __str__(self):
        daily = [f'{self.date}', f'{self.weight}', f'({self.bmi()})', f'{self.push_ups}', f'{self.squates}',
                 f'{self.steps}', f'{self.sleeptime}', f'{self.deep_sleeptime}', f'{self.temperature}', f'{self.sa}']
        return ' '.join(daily)

    def get_absolute_url(self):
        return f'/day/{self.pk}/'

    def bmi(self):
        """ Body mass index
        """
        return f'{round(float(self.weight) / 1.85 ** 2, 2)}'

    def dss(self):
        """ Deep sleep share
        """
        dss = self.deep_sleeptime.total_seconds() / self.sleeptime.total_seconds() * 100 if self.sleeptime.total_seconds() != 0 else 0
        return f'{round(dss, 1)}%'


class Tag(models.Model):
    """" Tags for thoughts
    """
    tag = models.CharField(max_length=32, blank=True, null=True)  # , unique=True)

    # note = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        db_table = 'tags'
        ordering = ('id',)

    def __str__(self):
        return self.tag


class Thought(models.Model):
    """ Thoughts of the day
    """
    timestamp = models.DateTimeField(default=timezone.now)
    record = models.TextField(blank=True, null=True)
    daily = models.ForeignKey(Daily, on_delete=models.DO_NOTHING, related_name='thoughts')
    tags = models.ManyToManyField(Tag, related_name='tags')

    class Meta:
        # managed = False
        db_table = 'thoughts'
        ordering = ('timestamp',)

    def __str__(self):
        # return str(self.timestamp.time) + ', ' + str(self.record)
        return f"{datetime.time(self.timestamp).strftime('%H:%M')} {self.record}"
        # words = self.record.split(' ')[:10]
        # return self.timestamp + ' ' + self.record

    def timestamp_brief(self):
        return f"{datetime.time(self.timestamp).strftime('%H:%M')}"

    def get_absolute_url(self):
        return reverse('thoughts:thought_detail', args=[self.pk])

desc/views.py
import atexit
import logging

from django.views.generic import ListView, DetailView
from rest_framework import generics, filters

from .models import Daily, Thought, Tag
from .serializers import DailySerializer, ThoughtSerializer, TagSerializer

logger = logging.getLogger(__name__)
logger.info("Application 'lifedesc' started.")


def at_exit():
    """
    Normal shutdown
    """
    logger.info("Application 'lifedesc' exited normally.")


atexit.register(at_exit)


class DailyLastListView(ListView):
    model = Daily
    ordering = '-date'
    template_name = 'daily_list_view.html'


class DailyDetailView(DetailView):
    model = Daily
    serializer_class = DailySerializer
    context_object_name = 'daily'
    template_name = 'daily_detail_view.html'


class DailyViewSet(generics.ListCreateAPIView):
    queryset = Daily.objects.all()
    serializer_class = DailySerializer


class DailyLastViewSet(generics.ListCreateAPIView):
    queryset = Daily.objects.order_by('-date')[:30]
    serializer_class = DailySerializer


class DailyDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Daily.objects.all()
    serializer_class = DailySerializer
    lookup_field = 'date'


class ThoughtListView(generics.ListCreateAPIView):
    serializer_class = ThoughtSerializer

    def get_queryset(self):
        desired_date = self.request.query_params.get('desired_date', None)
        queryset = Thought.objects.filter(timestamp__date=desired_date).order_by('timestamp')
        return queryset


class ThoughtsSearch(generics.ListAPIView):
    """ Search for thoughts on demand.
    """
    search_fields = ['record']
    filter_backends = (filters.SearchFilter,)
    queryset = Thought.objects.all()
    serializer_class = ThoughtSerializer


class AllTagsList(generics.ListAPIView):
    """ All possible tags.
    """
    queryset = Tag.objects.all()
    serializer_class = TagSerializer


def last(request, number=3):
    print('qqqq')
    queryset = Daily.objects.order_by('-date')[:number]
    return queryset

templates/daily_detail_view.html
{% load static %}
{% load is_holiday %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Detail</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    {% load estimate_tag %}
</head>
<body style="padding: 20px;">
<div class="container-fluid">
<div>
    <h2>{{ daily.date }} {{ daily.date|isdayoff }} </h2>
    <p>Вес: {{ daily.weight }} (Индекс массы тела:  <!--  style="padding-top: 1em" -->
        {% if daily.bmi|to_float >= 25  %}
            <span style="color: red;">{{ daily.bmi }}</span>
        {% else %}
            <span>{{ daily.bmi }}</span>
        {% endif %}
        ).</p>
    <p>Сделано: шагов - {{ daily.steps }}, отжиманий - {{ daily.push_ups }}, приседаний - {{ daily.squates }}.</p>
    <p>Продолжительность сна: всего - {{ daily.sleeptime }}, глубокий - {{ daily.deep_sleeptime }},
        доля глубокого сна -
        {% if daily.dss|to_float < 20  %}
            <span style="color: red;">{{ daily.dss }}</span>
        {% else %}
            <span>{{ daily.dss }}</span>
        {% endif %}
        .</p>
    <p>Утренняя температура: {{ daily.temperature }}.</p>
    <p>Оценка сна: {{ daily.sa }}.</p>
</div>
    <hr>
    <h3>Мысли</h3>
{#<div style="padding-left: 47px; text-indent: -47px;">#}
<div style="padding-left: 3em; text-indent: -3em;">
    {% for thought in daily.thoughts.all %}
        <p><i>{{ thought.timestamp_brief }}:</i> {{ thought.record }}  {# |linebreaks #}
        <br><i><span style="font-size: x-small; line-height: 0.3em; color: #808080">
            {% for tag in thought.tags.all %}
                {{ tag.tag }},
            {% endfor %}
            </span></i>
        </p>
    {% empty %}
        Мысли в этот день не отмечались
    {% endfor %}
</div>
<p><a class="btn btn-primary" href="{% url 'desc:daily_list' %}">К списку дней</a></p>
</div>
</body>
</html>

templates/daily_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body style="padding: 20px;">
<div class="container-fluid">
<h1>Dailies</h1>
<ul>
  {% for daily in object_list %}
  <li><a href="{{ daily.get_absolute_url }}">{{ daily }}</a></li>
  {% endfor %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&#171 первая </a>
            <a href="?page={{ page_obj.previous_page_number }}"> &#8249 предыдущая </a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"> следующая &#8250 </a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> последняя &raquo</a>
        {% endif %}
    </span>
  </div>
</ul>

</body>
</html>